import { MockDatabaseState } from './mock-database.models';

export const MOCK_DATABASE_SEED: MockDatabaseState = {
  currentUserId: 'user-frederik',
  isGuestSession: false,
  selectedChannelId: 'channel-dev',
  selectedThreadId: 'thread-angular-version',
  recentReactionEmojis: ['👍', '❤️', '😂', '😮'],
  users: [
    {
      id: 'user-frederik',
      name: 'Frederik Beck',
      email: 'frederik@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-1',
      isOnline: true,
    },
    {
      id: 'user-noah',
      name: 'Noah Braun',
      email: 'noah@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-3',
      isOnline: true,
    },
    {
      id: 'user-sofia',
      name: 'Sofia Müller',
      email: 'sofia@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-2',
      isOnline: false,
    },
    {
      id: 'user-mia',
      name: 'Mia Hansen',
      email: 'mia@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-4',
      isOnline: true,
    },
    {
      id: 'user-alice',
      name: 'Alice Becker',
      email: 'alice@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-1',
      isOnline: true,
    },
    {
      id: 'user-max',
      name: 'Max Mustermann',
      email: 'max@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-2',
      isOnline: false,
    },
    {
      id: 'user-sarah',
      name: 'Sarah Klein',
      email: 'sarah@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-3',
      isOnline: true,
    },
    {
      id: 'user-jonathan',
      name: 'Jonathan Bauer',
      email: 'jonathan@dabubble.dev',
      password: 'dabubble123',
      avatarClass: 'avatar-4',
      isOnline: false,
    },
    {
      id: 'user-guest',
      name: 'Gast',
      email: 'guest@dabubble.dev',
      password: 'guest',
      avatarClass: 'avatar-4',
      isGuest: true,
      isOnline: true,
    },
  ],
  channels: [
    {
      id: 'channel-dev',
      name: 'Entwicklerteam',
      description: 'Alles rund um Frontend, Angular und UI-Umsetzung.',
      memberIds: ['user-frederik', 'user-noah', 'user-sofia', 'user-mia', 'user-alice'],
      createdBy: 'user-frederik',
      createdAt: '2026-06-02T08:00:00.000Z',
      isPrivate: false,
    },
    {
      id: 'channel-design',
      name: 'Design',
      description: 'Mockups, Assets und visuelle Entscheidungen.',
      memberIds: ['user-frederik', 'user-sofia', 'user-sarah'],
      createdBy: 'user-sofia',
      createdAt: '2026-06-02T08:00:00.000Z',
      isPrivate: true,
    },
    {
      id: 'channel-general',
      name: 'Allgemein',
      description: 'Allgemeine Ankündigungen und Neuigkeiten für alle.',
      memberIds: ['user-noah', 'user-sofia', 'user-mia', 'user-alice', 'user-max', 'user-sarah'],
      createdBy: 'user-noah',
      createdAt: '2026-06-01T08:00:00.000Z',
      isPrivate: false,
    },
    {
      id: 'channel-marketing',
      name: 'Marketing',
      description: 'Kampagnen, Social Media und Außendarstellung.',
      memberIds: ['user-alice', 'user-max', 'user-sarah', 'user-jonathan'],
      createdBy: 'user-alice',
      createdAt: '2026-06-01T09:00:00.000Z',
      isPrivate: false,
    },
  ],
  messages: [
    {
      id: 'message-main-1',
      channelId: 'channel-dev',
      authorId: 'user-mia',
      body: 'Kurze Frage: Soll ich das Layout noch mehr wie im SVG ziehen oder lieber schon die Interaktion einbauen?',
      createdAt: '2026-06-02T13:12:00.000Z',
      reactions: [],
    },
    {
      id: 'message-main-2',
      channelId: 'channel-dev',
      authorId: 'user-frederik',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque blandit odio efficitur lectus vestibulum, quis accumsan ante vulputate. Quisque tristique iaculis erat, eu faucibus lacus iaculis ac.',
      createdAt: '2026-06-02T13:06:00.000Z',
      reactions: [{ emoji: 'check', count: 1, userIds: ['user-mia'] }],
    },
    {
      id: 'message-thread-origin',
      channelId: 'channel-dev',
      authorId: 'user-noah',
      body: 'Welche Version ist aktuell von Angular?',
      createdAt: '2026-06-02T12:25:00.000Z',
      reactions: [],
    },
    {
      id: 'message-thread-sofia',
      channelId: 'channel-dev',
      threadId: 'thread-angular-version',
      authorId: 'user-sofia',
      body: 'Ich habe die gleiche Frage. Ich habe gegoogelt und es scheint, dass die aktuelle Version Angular 13 ist. Vielleicht weiss Frederik, ob es wahr ist.',
      createdAt: '2026-06-02T12:30:00.000Z',
      reactions: [{ emoji: 'hands', count: 1, userIds: ['user-noah'] }],
    },
    {
      id: 'message-thread-frederik',
      channelId: 'channel-dev',
      threadId: 'thread-angular-version',
      authorId: 'user-frederik',
      body: 'Ja das ist es.',
      createdAt: '2026-06-02T13:06:00.000Z',
      reactions: [],
    },
  ],
  threads: [
    {
      id: 'thread-angular-version',
      channelId: 'channel-dev',
      originMessageId: 'message-thread-origin',
    },
  ],
  contactUserIds: ['user-noah', 'user-sofia', 'user-mia'],
};
